### ISSUE TITLE
how can i connect a printer using usb in windows?

### ISSUE THREAD

**Issue by FelipeSamuel** [BoboTiG/thermalprinter#19]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/thermalprinter/issues/19">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/thermalprinter/issues/19/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/thermalprinter/issues/19/pledge.svg">
</picture>
</a>

**Comment by BoboTiG** [comment]
Never tried on my side. Hopefully someone else could give a hand.

**Comment by BoboTiG** [comment]
Have a look on the [pyserial](https://github.com/pyserial/pyserial) side: it's the module used to connect/talk to the thermal printer.

**Comment by BoboTiG** [comment]
Since the version 1.0.0, the module should support any kind of serial connection thanks to the use of `serial_for_url()`:
https://github.com/BoboTiG/thermalprinter/blob/5fb1b10d4b8b6f0b5a1dd5fabfc73622a069fdee/src/thermalprinter/thermalprinter.py#L131

So, in theory, if `serial` works with your configuration, it should work with that project too.
